{% set version = "0.3.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-anytime
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/anytime_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/anytime/anytime_{{ version }}.tar.gz
  sha256: fe0295863ac8642364a00472d008647663d285f1a29a054a25a0cef732736b49

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-bh
    - r-rapidatetime
    - r-rcpp >=0.12.9
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-bh
    - r-rapidatetime
    - r-rcpp >=0.12.9

test:
  commands:
    - $R -e "library('anytime')"           # [not win]
    - "\"%R%\" -e \"library('anytime')\""  # [win]

about:
  home: http://dirk.eddelbuettel.com/code/anytime.html
  license: GPL (>= 2)
  summary: Convert input in any one of character, integer, numeric, factor, or ordered type into
    'POSIXct' (or 'Date') objects, using one of a number of predefined formats, and
    relying on Boost facilities for date and time parsing.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor

# Package: anytime
# Type: Package
# Title: Anything to 'POSIXct' or 'Date' Converter
# Version: 0.3.4
# Date: 2019-06-18
# Author: Dirk Eddelbuettel
# Maintainer: Dirk Eddelbuettel <edd@debian.org>
# Description: Convert input in any one of character, integer, numeric, factor, or ordered type into 'POSIXct' (or 'Date') objects, using one of a number of predefined formats, and relying on Boost facilities for date and time parsing.
# URL: http://dirk.eddelbuettel.com/code/anytime.html
# BugReports: https://github.com/eddelbuettel/anytime/issues
# License: GPL (>= 2)
# Encoding: UTF-8
# Depends: R (>= 3.2.0)
# Imports: Rcpp (>= 0.12.9), RApiDatetime
# LinkingTo: Rcpp (>= 0.12.9), BH, RApiDatetime
# Suggests: tinytest, gettz
# RoxygenNote: 6.0.1
# NeedsCompilation: yes
# Packaged: 2019-06-18 10:42:37.7923 UTC; edd
# Repository: CRAN
# Date/Publication: 2019-06-18 11:20:03 UTC
