{% set version = "0.3.9" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-anytime
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/anytime_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/anytime/anytime_{{ version }}.tar.gz
  sha256: 1096c15249ac70997a8a41c37eeb2a6d38530621abeae05d3dcd96a8acc7574a

build:
  number: 3
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-rcpp                     # [build_platform != target_platform]
    - r-bh                       # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-bh
    - r-rcpp >=0.12.9
  run:
    - r-base
    - r-rcpp >=0.12.9

test:
  commands:
    - $R -e "library('anytime')"           # [not win]
    - "\"%R%\" -e \"library('anytime')\""  # [win]

about:
  home: http://dirk.eddelbuettel.com/code/anytime.html
  license: GPL-2.0-or-later
  summary: Convert input in any one of character, integer, numeric, factor, or ordered type into 'POSIXct' (or 'Date') objects, using one of a number of predefined formats, and relying on Boost facilities for date and time parsing.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
    - philip-khor

# Package: anytime
# Type: Package
# Title: Anything to 'POSIXct' or 'Date' Converter
# Version: 0.3.6
# Date: 2019-08-29
# Author: Dirk Eddelbuettel
# Maintainer: Dirk Eddelbuettel <edd@debian.org>
# Description: Convert input in any one of character, integer, numeric, factor, or ordered type into 'POSIXct' (or 'Date') objects, using one of a number of predefined formats, and relying on Boost facilities for date and time parsing.
# URL: http://dirk.eddelbuettel.com/code/anytime.html
# BugReports: https://github.com/eddelbuettel/anytime/issues
# License: GPL (>= 2)
# Encoding: UTF-8
# Depends: R (>= 3.2.0)
# Imports: Rcpp (>= 0.12.9)
# LinkingTo: Rcpp (>= 0.12.9), BH
# Suggests: tinytest (>= 1.0.0), gettz
# RoxygenNote: 6.0.1
# NeedsCompilation: yes
# Packaged: 2019-08-29 11:14:20.265196 UTC; edd
# Repository: CRAN
# Date/Publication: 2019-08-29 12:00:02 UTC
