{% set version = "0.3.4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-anytime
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/anytime_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/anytime/anytime_{{ version }}.tar.gz
  sha256: 38d1ecd4b698f119076b8b4b1e39f39df0bd3eda928627014be04c3c1a6d78e0

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-bh
    - r-rapidatetime
    - r-rcpp >=0.12.9
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-bh
    - r-rapidatetime
    - r-rcpp >=0.12.9

test:
  commands:
    - $R -e "library('anytime')"           # [not win]
    - "\"%R%\" -e \"library('anytime')\""  # [win]

about:
  home: http://dirk.eddelbuettel.com/code/anytime.html
  license: GPL (>= 2)
  summary: Convert input in any one of character, integer, numeric, factor, or ordered type into
    'POSIXct' (or 'Date') objects, using one of a number of predefined formats, and
    relying on Boost facilities for date and time parsing.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
    - philip-khor
