appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: eG+o42wU0loAeJdZjTaP7Cjew8j5B4YmlS5EI07M70TpqeigQwKWvLeNlHWJme90UE5hYAHgojjap+o2/MricTdh8QC2SpbqIwCV2gmvP5kZHLAfoxoRHHR4qfg/E2LloYt5H2OyOsZ1BQWcjbvAhXYWVb0H12a/vMnRIQ8VA0CvrvNG4iRCF92j5xE3LKCLZIYte/1K1ySEhQPyXZlFouaoYDPDeJWe5OOv6s5JZeKF/sJvPM/5SQ6ikT/sobaLOzllarlETivUQijdCL47OP2wlYhrsNJvYDRjk2YWSG9tYCGjx99EVdFAB5K6rVP4UZ1pT59BJ269rR1+MXPdg6WH2smRbqyuTm9u5pN6mpo3xedBL6BtpXv5/1qzYE1Dy/DZKt/G7Qr/8bxxk3CstvWSTB0TfRg54qmr0AvNRMxE2V1z7j07jJl3ZsClKq+KRwY8/ccsDKhvr7uEtKV1OD937FHDfnR03MbGDWN6C+k2Hv86x0rF1v4OZLvWSWSuLHdIZJ978t6HuB2ltpHwcBd1jA3KHO7Jrc8Nx3UHL7hmNTC4vUuMUYqNO93ZNu0znbJSSsXn/ARlkowp9KKNelV7Q7IPogIL/1eHdCyAUn1YT+QYi4Mty168+tzJiNjNxGphKbP+MOg/eAmekIoTZqeCMA8Ozb90WtgsMUHhIjE=
